### ISSUE TITLE
Adjust player pathing issues chapter by chapter

### ISSUE THREAD

**Issue by Spider-Man1212** [gb2dev/HLA-NoVR#28]
Remaining maps:

- [x] a3_hotel_lobby_basement
- [x] a3_hotel_underground_pit
- [x] a3_hotel_interior_rooftop
- [x] a3_hotel_street
- [x] a3_c17_processing_plant
- [x] a3_distillery
- [x] a4_c17_zoo
- [x] a4_c17_tanker_yard
- [x] a5_vault
- [x] a5_ending

**Comment by SpaceMageWhatever** [comment]
i think theres a spot where you need to jump in an elevator shaft, where its really hard to make the jump sideways and you can either fall right next to the shaft and miss the ladder entirely or fall forward because theres nothing to stand on

chapter 6 has a light near the broken catwalk at the start of the level that gets in the way, if you jump you can bump into it and fall to your death, the jump height also feels too small so the jumping feels a bit too precise and its easy to fall and die, or maybe you are not supposed to jump the gap? i dont know what the design was supposed to be like there

**Comment by gb2dev** [comment]
Done
